### ISSUE TITLE
Detailed view of a product

### ISSUE THREAD

**Issue by layerok** [layerok/emojisushi-front#22]

**Comment by vovarudomanenko** [comment]
https://www.figma.com/file/pxicBIbHY1xll9Ii92pA8q/Emoji?type=design&node-id=2076-3548&mode=design&t=j8r1g8w977eQ1EQn-0

**Comment by vovarudomanenko** [comment]
/product/zapechinij-syke-chiz

**Comment by vovarudomanenko** [comment]
open the modal on a product card click
