### ISSUE TITLE
move "refund policy" page to the footer

### ISSUE THREAD

**Issue by layerok** [layerok/emojisushi-front#25]
<img width="1200" alt="image" src="https://github.com/vovarudomanenko/emojisushi-front/assets/18424848/0e94f03e-7c69-4e45-9910-71448e1104eb">

**Comment by vovarudomanenko** [comment]
![image](https://github.com/vovarudomanenko/emojisushi-front/assets/18424848/1f67c08f-9399-4bbf-ab43-30aa9144bd64)
justify map
