### ISSUE TITLE
Scroll offset persists between page navigations

### ISSUE THREAD

**Issue by layerok** [layerok/emojisushi-front#6]
For example, when a user navigates to the checkout page, suddenly the newly opened page has the same scroll offset as the previous page.

This is bad UX because a user must first realize that he is not at the top of the page, which is not so obvious and takes some time. And secondly he must manually scroll up to the top of the page in order to be able to fill out a checkout form.

Steps to reproduce:
1. Visit /category/{{slug}} page
2. Scroll down the page some distance
3. Open the cart modal
4. Click the 'checkout' button

The screenshot below demonstrates the state of the checkout page after navigating from a page with a scroll offset. As you can see the checkout page is scrolled to the very bottom
![image](https://github.com/vovarudomanenko/emojisushi-front/assets/18424848/7a224668-e256-4a2b-9bcb-b8db0d04cc5e)

**Comment by vovarudomanenko** [comment]
Naïve solution is to scroll up the newly opened page to the top.

**Comment by layerok** [comment]
adding ```<ScrollRestoration/>``` component fixed this issue
